apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hallo-ns
  labels:
    app: hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-container
          image: danyeu/hello-world:spring-docker
          ports:
            - containerPort: 8080